language: swift
osx_image: xcode9.3
env:
  global:
    - SDK=macosx
    - TARGET=x86_64-apple-darwin17.5.0
  matrix:
    - PLAYGROUND_DIR="Chapter 1/Floating Point Approximates.playground"
    - PLAYGROUND_DIR="Chapter 1/Floating Point Environment.playground"
    - PLAYGROUND_DIR="Chapter 2/Cardinal Numbers.playground"
    - PLAYGROUND_DIR="Chapter 2/Currencies.playground"
    - PLAYGROUND_DIR="Chapter 2/Custom Formats.playground"
    - PLAYGROUND_DIR="Chapter 2/Decimal Numbers.playground"
    - PLAYGROUND_DIR="Chapter 2/Integer and Fraction Digits.playground"
    - PLAYGROUND_DIR="Chapter 2/Ordinal Numbers.playground"
    - PLAYGROUND_DIR="Chapter 2/Percentages.playground"
    - PLAYGROUND_DIR="Chapter 2/Rounding Modes.playground"
    - PLAYGROUND_DIR="Chapter 2/Scientific Notation.playground"
    - PLAYGROUND_DIR="Chapter 2/Significant Digits.playground"
    - PLAYGROUND_DIR="Chapter 3/Currency Converter.playground"
    - PLAYGROUND_DIR="Chapter 3/Money.playground"
    - PLAYGROUND_DIR="Chapter 4/Configuring Precision.playground"
    - PLAYGROUND_DIR="Chapter 4/Natural Scale.playground"
    - PLAYGROUND_DIR="Chapter 4/Provided Units.playground"
    - PLAYGROUND_DIR="Chapter 4/Temperature Formatting.playground"
    - PLAYGROUND_DIR="Chapter 4/Units Interoperability.playground"
    - PLAYGROUND_DIR="Chapter 5/Agricultural Flight Planner.playground"

script:
  xcrun swift --version &&
  cd "${PLAYGROUND_DIR}" &&
  if ! xcrun swiftc -emit-imported-modules Contents.swift |
          grep -q "PlaygroundSupport";
  then
    if [[ -n $(find . -name "Sources") ]];
    then
      echo "import AuxiliarySources" | cat - Contents.swift > main.swift &&
      xcrun -sdk "${SDK}"
        swiftc -target "${TARGET}"
              -emit-library -emit-module -module-name AuxiliarySources
              Sources/*.swift &&
      xcrun -sdk "${SDK}"
        swiftc -target "${TARGET}"
               -I "." -L "."
               -lAuxiliarySources
               -module-link-name AuxiliarySources
               -o Playground main.swift;
    else
      xcrun -sdk "${SDK}"
        swiftc -target "${TARGET}"
               -o Playground Contents.swift;
    fi;
  fi;
